### ISSUE TITLE
Allow P4 default actions to be updated at runtime

### ISSUE THREAD

**Issue by jhsmt** [p4tc-dev/linux-p4tc-pub#21]
Note, in P4TC we have a default hit action in addition to a default miss action.

We need to define whether these actions can be update at runtime.
We borrow and extend from ForCES (see RFC 5812). Table default actions
will have two permissions defined at template table definition time. 

1) Control-plane permissions. At the moment Read, Update, Delete are the only ones needed.
This means if a template defines a default table action to have per-entry RUD then the control plane
can RUD i.e Read, Update and Delete (note "delete" may not make a lot of sense here - so we should probably
disallow).

2) Data-path permissions. At the moment we assume that the datapath cannot update the default actions

Example, per Andy's notes here:
https://github.com/jafingerhut/p4-guide/blob/master/docs/p4-table-behaviors.md
We should use the "const" keyword to define whether a table's default action can be updated at runtime or not.
Table below can have its table default hit action updated from a2() to any of a1, a3, a4 but it cannot have
its default miss action updated from a3()

    table t1 {
        key = {
            hdr.ethernet.srcAddr : ternary;
        }
        actions = {
            a1; @default_hit_candidate
            a2; @default_hit_candidate, @default_hit
            a3; @default_hit_candidate
            a4; @default_hit_candidate
        }
	size = 16;
       const default_action = a3();
    }

iow, "constant" is mapped to read-only permissions.

Sosutha points out that we can only specify default hit action via annotations;
however, if we have multiple potential candidates the question is how would the compiler
tell us? Above is an attempt at specifying all actions that could be used as default hit 
action but isolating a2() as the one we start with.

**Comment by Sosutha** [comment]
Could you explain the difference between @default_hit_candidate and @default_hit annotations.
All the actions present inside the table can be used for the table entries.
default_action is the one that gets executed when there is a miss.
My understanding for "@default_hit" is, it denotes the action that gets executed when there is a hit but no action specified for the same. Please correct if I am wrong

**Comment by jhsmt** [comment]
You are correct, but i ran into what i thought was an ambiguity.

Since we cant say: "default_hit = a3();" you suggested earlier an approach you use annotations
which means we dont need a language spec change i.e.

    actions = {
        a1; 
        a2;  @default_hit
        a3; 
        a4; 
    }
   size = 16;
   const default_action = a3();

Now suppose i wanted to allow a1, a2, a3 to be hit action candidates - how would i specify that?
What seemed legitimate is to invent another annotation - lets call it "@default_hit_candidate"
so then above becomes:

    actions = {
        a1; @default_hit_candidate;
        a2;  @default_hit_candidate;
        a3; @default_hit, @default_hit_candidate;
        a4; @default_hit_candidate;
    }
   size = 16;
   const default_action = a3();

But if i wanted to specify a2 as both the initial default_hit action as well as a default_hit_candidate
then i would need both annotations for it as specified above. Not sure if you are allowed multiple
annotations (or if the delimiter is a ",") ......

**Comment by Sosutha** [comment]
When you add action inside the table, they all become hit action candidates. So there is no need of @default_hit_candidate annotation.

**Comment by jhsmt** [comment]
I suppose if you wanted some action (example a4) not to be a candidate you would need another annotation
(@nodefault_hit)?
Also - how do we say the default hit action is "const"

**Comment by Sosutha** [comment]
https://p4.org/p4-spec/docs/p4-16-working-draft.html#sec-table-action-anno
From the P4 spec section mentioned above, any action which has @tableonly annotation is not a candidate for default action. We do not need another annotation. We can make use of @tableonly.

Since we can define the semantics of the annotation, we can define that any action with annotation @default_hit is constant as well. If we have two different requirements with and without constant, then we can define two different annotation @default_hit_const and @default_hit.

**Comment by jhsmt** [comment]
Ok, probably I am overthinking on the "no candidate" - lets see what deployment brings forward.

on the hit constant, yes having both @default_hit_const and @default_hit will help.

We are working on the template syntax - we will update with syntax when implementation is done

**Comment by jhsmt** [comment]
For completion, we implemented a very generic approach which separates what
the datapath vs control path allowed permissions.

As an example, here's the syntax that the compiler will generate for permissions

$TC p4template update table/myprog/mytable \
default_miss_action permissions 0x30F action mydefault_miss_action

                    CRUDXCRUDX
0x30F in binary is (1100001111), which means we have only Create and
Read permissions in the control plane and Read, Update, Delete and
eXecute permissions in the data plane. This means, for above example, that now
we can only delete the default miss action from the data plane. The only
exception is the delete pipeline command, which always will delete the
table and its default actions independent of their permissions.

For a const miss action - where we dont allow  either the dataplane or
the control plane to delete/update it then the permissions are:
-R---XR--X

**Comment by Sosutha** [comment]
Please confirm if the default hit action would like below

$TC p4template update table/myprog/mytable
default_hit_action permissions 0x30F action mydefault_hit_action

**Comment by jhsmt** [comment]
In current P4 you only need to worry about default actions being "const" or not.
0x30F was a bad example. Lets start with all the 10 bits used in permissions:
CRUDXCRUDX bit maps to 11111111111 = 0x03FF

1) For a const mydefault_hit_action we want to make permission
      -R----R--X which is:0100001001 = 0x0109
i.e:
$TC p4template update table/myprog/mytable \
default_hit_action permissions 0x109 action mydefault_hit_action

2) For non-const, you(compiler) **dont have to specify permissions** i.e the default is assumed.
i.e it is sufficient to say:
$TC p4template update table/myprog/mytable \
default_hit_action action mydefault_hit_action

but, if you do specify permissions, it will be:
     -RUD--RUDX which is 0111001111 0x01CF i.e
$TC p4template update table/myprog/mytable \
default_hit_action permissions 0x1CF action mydefault_hit_action

Note:
If we have a unique action (not "NoAction") for either hit or miss then it needs to be created first per usual
way of creating actions.  Essentially, default_hit_action + default_miss_action
are properties of the table; when you dont specify them you will get the defaults which are essentially noactio
