### ISSUE TITLE
Add cmd labels to ease debug-ability

### ISSUE THREAD

**Issue by jhsmt** [p4tc-dev/linux-p4tc-pub#46]
Consider the following table apply:

    apply {
        if (hdr.p4calc.isValid()) {
            calculate.apply();
        } else {
            operation_drop();
        }
}

This fits in pipeline preaction as such:

$TC p4template create action/calc/PPREA \
   cmd beq hdrfield.calc.1.calc.isValid constant.bit1.1 control pipe / jump 2 \ <----- if
   cmd tableapply table.calc.MyIngress/calculate \
   cmd bne hdrfield.calc.1.calc.isValid constant.bit1.1 control pipe / ok \  <------- end of if, start of else
  cmd set metadata.calc.global/drop constant.bit1.1 

If a human (we expect humans to interfere, what else is new) enters a print for debug as such:

$TC p4template create action/calc/PPREA \
   cmd beq hdrfield.calc.1.calc.isValid constant.bit1.1 control pipe / jump 2  \ <----- if
   cmd print prefix PPREAarrivedat metadata.kernel.iif \
   cmd print prefix check_drop_val metadata.calc.global/drop constant.bit1.1  \
   cmd tableapply table.calc.MyIngress/calculate \
   cmd bne hdrfield.calc.1.calc.isValid constant.bit1.1 control pipe / ok  \  <------- end of if, start of else
  cmd set metadata.calc.global/drop constant.bit1.1 

Note: they forgot to change "jump 2" to be "jump 3" - which will end up not executing the drop.

Lets introduce labels to resolve this issue but also makes it easier for the compiler to have
simpler patters. A slightly more exaggerated version of above pipeline preaction is as follows:

$TC p4template create action/calc/PPREA \
  cmd print prefix PPREAarrivedat metadata.kernel.iif \
  cmd print prefix PPREADir metadata.kernel.direction \
  cmd print prefix if hdrfield.calc.1.calc.isValid \
  cmd beq hdrfield.calc.1.calc.isValid constant.bit1.1 control pipe / jump else \
  cmd tableapply table.calc.MyIngress/calculate \
  cmd print prefix endif hdrfield.calc.1.calc.isValid \
  cmd jump endif \
  cmd label else \
  cmd print prefix else hdrfield.calc.1.calc.isValid \
  cmd set metadata.calc.global/drop constant.bit1.1 \
  cmd label endif

Thats all the compiler needs to do (and ofcourse let the human go nuts if they want to).

The kernel will insert the correct jump _numeric_ values (and will reject if labels are in the wrong spot;
 - example you cant jump past the end and at the moment we are not allowing backward jumps)

**Comment by vbnogueira** [comment]
Closed by #51
