### ISSUE TITLE
Add supported actions list to table in P4TC

### ISSUE THREAD

**Issue by vbnogueira** [p4tc-dev/linux-p4tc-pub#64]
A P4 table has a list of actions it supports, for example:

```
table smac {
    key = { outCtrl.outputPort : exact; }
    actions = {
        Drop_action;
        Rewrite_smac;
    }
}
```

We must support this in P4TC.

The actions list specifies which actions may be used as default actions of this table or as a table entry action.

If the action is meant only as a default one, we should use the flag `defaultonly`.
If the action is meant only as a table entry action, we should use the flags `tableonly`.

So this is the list of possible table flags:

- defaultonly
- tableonly

For example:

```
tc p4template create table/redirect_srcip/MainControlImpl/nh_table_srcip \                                                                 
        tblid 3  keysz 32 type exact tentries 2048 nummasks 32 \                                                                           
        table_acts act name redirect_srcip/MainControlImpl/send_nh flags tableonly \                                                         
        act name redirect_srcip/MainControlImpl/default_drop flags defaultonly
```

In the above sample, action redirect_srcip/MainControlImpl/send_nh can only be used as a table entry action.
And action redirect_srcip/MainControlImpl/default_drop can only be used as a default action.

If the action has no flags, it means it can be used as both default and table entry action.
Those are the only two flags we currently have for table actions.

**Comment by vbnogueira** [comment]
Closed by #55

**Comment by Sosutha** [comment]
We had two other flags for the table actions namely
@default_hit_const
@default_hit

If an action has these annotations in P4, What flags need to be emitted for those actions in the template file?
Can we use defaultHitConst and defaultHit respectively. Please confirm

**Comment by vbnogueira** [comment]
> We had two other flags for the table actions namely @default_hit_const @default_hit
> 
> If an action has these annotations in P4, What flags need to be emitted for those actions in the template file? Can we use defaultHitConst and defaultHit respectively. Please confirm

We don't use an annotation for `defaultHit`, instead we create it as a table attribute.

For example, imagine we created the following table:

tc p4template create table/redirect_srcip/MainControlImpl/nh_table_srcip \                                                                 
        tblid 3  keysz 32 type exact tentries 2048 nummasks 32 \                                                                           
        table_acts act name redirect_srcip/MainControlImpl/send_nh \                                                         
        act name redirect_srcip/MainControlImpl/default_drop \
        act name redirect_srcip/MainControlImpl/default_accept
        
If we want to add a default hit action to it, we'd issue the following command:

tc p4template update table/redirect_srcip/MainControlImpl/nh_table_srcip \                                                                 
        default_hit_action redirect_srcip/MainControlImpl/default_accept
        
In the above example, we are updating the `default hit action` to action `redirect_srcip/MainControlImpl/default_accept`

If, however, we want the `default hit action` to also be `constant` (`defaultHitConst`), we use the permission attributes.

For example, to make `redirect_srcip/MainControlImpl/default_accept` a `constant default hit action` we'd issue the following command:

tc p4template update table/redirect_srcip/MainControlImpl/nh_table_srcip \                                                                 
        default_hit_action redirect_srcip/MainControlImpl/default_accept permissions 0x109


Remember that we use CRUDXCRUDX permissions, where the first five bits are for control plane permissions and the last five are for data path permissions.

This means that `0x109` corresponds to `-R---R--X`  permissions. So the control plane can only `read` the default hit action and the data path can only `read and execute` it. Which makes the default hit action `constant`.

**Comment by Sosutha** [comment]
Ok. so tableonly and defaultonly are flags supported in template file.
default_hit and default_hit_const are table attributes. 

Additionally, FYI, In p4, when you need to specify an action as default_hit action, you need to annotate the action as below.
This will allow the P4TC compiler to generate the table attribute in template file

table redirect_srcip {
        key = { hdr.ipv4.srcaddr : exact; }
       actions = {
         send_nh ;
         default_drop;
         default_accept   @default_hit;
       }
}
